include:
  - compose.data.yaml

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    command: --spring.profiles.active=database
    ports:
      - '8080:8080'
