include:
  - ./infrastructure/compose.data.yaml
  - ./infrastructure/compose.monitoring.yaml

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    command: --spring.profiles.active=cache
    ports:
      - '8080:8080'
